name: "Manual Export"
on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: 'Version of engine to build e.g. "3.4.4", "3.5"'
        required: true
        default: "3.5"
      release_name:
        description: 'Release name, usually "stable", but can also be something like "rc3", "beta1"'
        required: true
        default: "stable"
      export_platform:
        description: "Export Platform - all|windows|linux|web|android"
        required: true
        default: "windows"
      export_folder:
        description: "Export Folder - Repository Path"
        required: true
        default: "."
      export_name:
        description: "Export Name"
        required: true
        default: "trashy_baboon"
      release_android:
        description: "Android Release Build"
        required: false
        default: "false"
      itch_io:
        description: "Itch.io Build"
        required: false
        default: "false"

env:
  GODOT_VERSION: ${{ github.event.inputs.godot_version }}
  RELEASE_NAME: ${{ github.event.inputs.relaease_name }}
  EXPORT_PLATFORM: ${{ github.event.inputs.export_platform }}
  EXPORT_FOLDER: ${{ github.event.inputs.export_folder }}
  EXPORT_NAME: ${{ github.event.inputs.export_name }}
  RELEASE_ANDROID: ${{ github.event.inputs.release_android }}
  ITCH_IO: ${{ github.event.inputs.itch_io }}

jobs:
  export_windows:
    name: Windows Export
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.export_platform == 'windows' || github.event.inputs.export_platform == 'all' }}
    container:
      image: sxmxc/godot-rc-ci:3.5-rc5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME} ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME}
      - name: Windows Build
        run: |
          cd ${EXPORT_FOLDER}
          mkdir -v -p build/windows
          godot -v --export "Windows Desktop" ./build/windows/${EXPORT_NAME}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${EXPORT_NAME}
          path: ${{ env.EXPORT_FOLDER }}/build/windows
      - name: Zip Folder
        run: zip -r itch.zip ${{ env.EXPORT_FOLDER }}/build/windows
      - name: Deploy to itch.io
        if: ${{ env.ITCH_IO == true }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch.zip

  export_linux:
    name: Linux Export
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.export_platform == 'linux' || github.event.inputs.export_platform == 'all' }}
    container:
      image: sxmxc/godot-ci:3.5-rc5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME} ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME}
      - name: Linux Build
        run: |
          cd ${EXPORT_FOLDER}
          mkdir -v -p build/linux
          godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Linux
          path: ${{ env.EXPORT_FOLDER }}/build/linux
      - name: Zip Folder
        run: zip -r itch.zip ${{ env.EXPORT_FOLDER }}/build/linux
      - name: Deploy to itch.io
        if: ${{ env.ITCH_IO == true }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch.zip

  export_web:
    name: Web Export
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.export_platform == 'web' || github.event.inputs.export_platform == 'all' }}
    container:
      image: sxmxc/godot-ci:3.5-rc5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME} ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME}
      - name: Web Build
        run: |
          cd ${EXPORT_FOLDER}
          mkdir -v -p build/web
          godot -v --export "HTML5" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Web
          path: ${{ env.EXPORT_FOLDER }}/build/web
      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ${{ env.EXPORT_FOLDER }}/build/web # The folder the action should deploy.
      - name: Zip Folder
        run: zip -r itch.zip ${{ env.EXPORT_FOLDER }}/build/web
      - name: Deploy to itch.io
        if: ${{ env.ITCH_IO == true }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: HTML
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch.zip

  export_android:
    name: Android Export
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.export_platform == 'android' || github.event.inputs.export_platform == 'all' }}
    container:
      image: davcri/godot-game-template-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mkdir -v -p ~/.config/godot/
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME} ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME}
          cp /root/.config/godot/editor_settings-3.tres ~/.config/godot/editor_settings-3.tres
          echo 'export/android/debug_keystore = "/root/debug.keystore"' >> ~/.config/godot/editor_settings-3.tres
          echo 'export/android/android_sdk_path = "/root/android-sdk"' >> ~/.config/godot/editor_settings-3.tres
      - name: Android Debug Build
        run: |
          cd ${EXPORT_FOLDER}
          mkdir -v -p build/android
          godot --verbose --export-debug "Android-CI-job (Do not edit)" ./build/android/$EXPORT_NAME.debug.apk
      - name: Android Release Build
        if: ${{ env.RELEASE_ANDROID == true }}
        env:
          K8S_SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_BASE64 }}
          K8S_SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_USER  }}
          K8S_SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_PASSWORD  }}
        run: |
          echo $K8S_SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > /root/release.keystore
          sed 's@keystore/release[[:space:]]*=[[:space:]]*".*"@keystore/release = "/root/release.keystore"@g' -i export_presets.cfg
          sed 's@keystore/release_password[[:space:]]*=[[:space:]]*".*"@keystore/release_password="'$K8S_SECRET_RELEASE_KEYSTORE_PASSWORD'"@g' -i export_presets.cfg
          sed 's@keystore/release_user[[:space:]]*=[[:space:]]*".*"@keystore/release_user="'$K8S_SECRET_RELEASE_KEYSTORE_USER'"@g' -i export_presets.cfg
          cd ${EXPORT_FOLDER}
          godot --verbose --export "Android" ./build/android/$EXPORT_NAME.release.apk
      - uses: actions/upload-artifact@v1
        with:
          name: Android
          path: ${{ env.EXPORT_FOLDER }}/build/android
      - name: Zip Folder
        run: zip -r itch.zip ${{ env.EXPORT_FOLDER }}/build/android
      - name: Deploy to itch.io
        if: ${{ env.ITCH_IO == true }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: android
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch.zip
